In [1]:
import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd 
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.svm import SVC

In [2]:
df = pd.read_csv("../DataSet/GalaxyZooSDSSDataset.csv")
df.keys()

Index(['Unnamed: 0', 'OBJID', 'RA', 'DEC', 'NVOTE', 'P_EL', 'P_CW', 'P_ACW',
       'P_EDGE', 'P_DK', 'P_MG', 'P_CS', 'P_EL_DEBIASED', 'P_CS_DEBIASED',
       'SPIRAL', 'ELLIPTICAL', 'UNCERTAIN', 'ra', 'dec', 'run', 'field',
       'type', 'dered_g', 'dered_r', 'dered_i', 'deVAB_i', 'expAB_i',
       'lnLExp_i', 'lnLDeV_i', 'lnLStar_i', 'petroR90_i', 'petroR50_i',
       'mRrCc_i', 'mCr4_i', 'texture_i', 'Type', 'dered_g-dered_r',
       'dered_r-dered_i'],
      dtype='object')

In [3]:
dfE = df[df.Type == "Elliptical"]
dfS = df[df.Type == "Spiral"]

Take a real astrophysical data set or generate random data with two classes and THREE features.

In [26]:
f, (ax,bx) = plt.subplots(1,2,figsize=(11,8))
ax.scatter(dfE.dered_r + 6,dfE.dered_g - dfE.dered_i,color="black",zorder =1)
ax.scatter(dfS.dered_r,dfS.dered_g - dfS.dered_i,zorder=0)
ax.set_ylim(-5,5); ax.set_xlim(10,30)
ax.set_ylabel("G - I"); ax.set_xlabel("R")

bx.scatter(dfE.dered_r + 7,dfE.dered_r - dfE.dered_i + .5,color="black",zorder =1)
bx.scatter(dfS.dered_r,dfS.dered_r - dfS.dered_i,zorder=0)
bx.set_ylim(-8,2); 
bx.set_ylabel("R - I"); bx.set_xlabel("R");

In [5]:
half = int(np.ceil(len(df.dered_r)/2))

data = np.zeros([len(df.dered_r[:half]),2])
data[:,0] = df.dered_r[:half] + 6 
data[:,1] = df.dered_g[:half] - df.dered_i[:half];

labels = df.Type[:half]

Plot the data set with decision boundary, margins, and label the support vectors from SVM.

In [24]:
svc = SVC(C= 1.0, kernel='linear')

In [25]:
svc.fit(data,labels)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
data.shape, labels.shape

((128067, 2), (128067,))

- Plot the data set with decision boundary, margins, and label the support vectors from SVM.

In [8]:
p_x,p_y = np.meshgrid(np.arange(10,30,.1),np.arange(-5,5,.1))


In [12]:
decision_function = svc.decision_function(np.c_[p_x.ravel(),p_y.ravel()])

In [13]:
plt.contour(p_x,p_y,decision_function.reshape(p_x.shape))

ValueError: cannot reshape array of size 60000 into shape (100,200)

In [22]:
np.shape(p_x), np.shape(p_y)

((100, 200), (100, 200))

In [15]:
np.shape(decision_function)

(20000, 3)

In [17]:
np.shape(data)

(128067, 2)

In [18]:
p_x.ravel()

array([10. , 10.1, 10.2, ..., 29.7, 29.8, 29.9])

In [19]:
p_x.flatten()

array([10. , 10.1, 10.2, ..., 29.7, 29.8, 29.9])

In [21]:
np.c_[p_x.ravel(),p_y.ravel()]

array([[10. , -5. ],
       [10.1, -5. ],
       [10.2, -5. ],
       ...,
       [29.7,  4.9],
       [29.8,  4.9],
       [29.9,  4.9]])